resolver: https://raw.githubusercontent.com/pgenie-io/stack-snapshot/015bc2cdae18e2b51f710a29ea08c90f64a9def3/snapshot.yaml
extra-deps:
  - url: https://github.com/nikita-volkov/http-client/archive/fb7bf1fd2153b02120ae34190d5ef60510f4c67a.tar.gz
    subdirs:
      - http-client
      - http-client-tls
  - url: https://github.com/nikita-volkov/hs-connection/archive/acba33e8552bb738314c916333a8dcacaa9ec027.tar.gz
