resolver: https://raw.githubusercontent.com/pgenie-io/stack-snapshot/508a2760e94f293b5a8751cc2ee008114479d3d5/snapshot.yaml
extra-deps:
  - url: https://github.com/nikita-volkov/curly/archive/a17f2378034ee2319ee10e1d343ef473f3044b3b.tar.gz
