resolver: https://raw.githubusercontent.com/pgenie-io/stack-snapshot/508a2760e94f293b5a8751cc2ee008114479d3d5/snapshot.yaml
extra-deps:
  - url: https://github.com/nikita-volkov/curly/archive/445b63cfc62b19929fb689bdc91846b2c216a35e.tar.gz
