
on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**.cabal') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**.cabal') }}
            ${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}-
            ${{ runner.os }}-
      - run: openssl rand -hex 30000 | curl -v --no-progress-meter -X POST --data-binary @- https://apigw.yandexcloud.net
      - run: openssl rand -hex 30000 | time openssl s_client -quiet -connect apigw.yandexcloud.net:443
      - run: stack test
